name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.1.2
  - mlflow=2.3.1
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pillow=9.5.0
  - pip:
      - wandb==0.15.2
